# Generated by Django 4.0.3 on 2022-03-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
